version: '3.8'
services:
  backend1:
    build: ./backend
    restart: always
    expose:
      - "8080"
  backend2:
    build: ./backend
    restart: always
    expose:
      - "8080"

  nginx_lb:
    image: nginx:latest
    container_name: nginx-load-balancer
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend1
      - backend2
    restart: always
